apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
   name: pizza-gw
spec:
   gatewayClassName: gke-l7-regional-external-managed
   listeners:
      - name: proxy
        port: 443
        protocol: HTTPS
        tls:
           mode: Terminate
           options:
              networking.gke.io/pre-shared-certs: ordenginering-com
