apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: pizza-jwt
  labels:
    app: pizza-jwt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizza-jwt
  template:
    metadata:
      name: pizza-jwt
      labels:
        app: pizza-jwt
    spec:
      containers:
        - name: pizza-jwt
          image: diegoj4v/pizza-jwt:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 80
              path: /jwt/health/readiness
            initialDelaySeconds: 40
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 4
          livenessProbe:
            httpGet:
              port: 80
              path: /jwt/health/liveness
            initialDelaySeconds: 40
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 4
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 200m
              memory: 240Mi
            requests:
              cpu: 120m
              memory: 100Mi
          env:
            - name: SERVER_PORT
              value: "80"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-key
            - name: MYSQL_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_domain
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_password
            - name: RABBIT_PROTOCOL
              value: "amqps"
            - name: RABBIT_PORT
              value: "5671"
            - name: RABBIT_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-host
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-user
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-password

---
apiVersion: v1
kind: Service
metadata:
  name: pizza-jwt-svc
spec:
  selector:
    app: pizza-jwt
  ports:
    - port: 80
      targetPort: 80