apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: pizza-ingredient
  labels:
    app: pizza-ingredient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizza-ingredient
  template:
    metadata:
      name: pizza-ingredient
      labels:
        app: pizza-ingredient
    spec:
      containers:
        - name: pizza-ingredient
          image: diegoj4v/pizza-ingredient:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /ingredient/actuator/health/readiness
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 4
          livenessProbe:
            httpGet:
              port: 8080
              path: /ingredient/actuator/health/liveness
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 4
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 480Mi 
            requests:
              cpu: 200m
              memory: 480Mi
          env:
            - name: "JAVA_OPTS"
              value: "-Xmx75M -XX:MaxMetaspaceSize=256M -XX:+UseG1GC -XX:ReservedCodeCacheSize=64M -Xss256K"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SERVER_PORT
              value: "8080"
            - name: MYSQL_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_domain
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_password
            - name: JWT_SERVICE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: client-configmap
                  key: jwt_domain
            - name: BUCKET_ACCESSKEYID
              valueFrom:
                secretKeyRef:
                  name: bucket-secret
                  key: aws_access_key
            - name: BUCKET_SECRETACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: bucket-secret
                  key: aws_secret_key
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: bucket-secret
                  key: aws_bucket

---
apiVersion: v1
kind: Service
metadata:
  name: pizza-ingredient-svc
spec:
  selector:
    app: pizza-ingredient
  ports:
    - port: 80
      targetPort: 8080
